CREATE TABLE OpenTimes (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	WeekdayStart DATETIME NOT NULL,
	WeekdayEnd DATETIME NOT NULL,
	WeekendStart DATETIME NOT NULL,
	WeekendEnd DATETIME NOT NULL
)

CREATE TABLE Admins (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(MAX) NOT NULL,
	LastName NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
	Password NVARCHAR(MAX) NOT NULL
)

Create TABLE Streets (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StreetName NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Cities (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CityName NVARCHAR(MAX) NOT NULL,
	Zip INT NOT NULL
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CityId INT FOREIGN KEY REFERENCES Cities(Id) NOT NULL,
	StreetId INT FOREIGN KEY REFERENCES Streets(Id) NOT NULL,
	Nr INT NOT NULL
)

CREATE TABLE Unions (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE UnionLeaders (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UnionId INT FOREIGN KEY REFERENCES Unions(Id) NOT NULL,
	FirstName NVARCHAR(MAX) NOT NULL,
	LastName NVARCHAR(MAX) NOT NULL,
	Phone INT NOT NULL,
)

CREATE TABLE Activities (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ActivitiName NVARCHAR(MAX) NOT NULL,
	RequiredSpace INT NOT NULL
)

CREATE TABLE Reservations (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ActivityId INT FOREIGN KEY REFERENCES Activities(Id) NOT NULL,
	Accepted BIT NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL
)

CREATE TABLE ReservationTimes (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ReservationsId INT FOREIGN KEY REFERENCES Reservations(Id) NOT NULL,
	[Date] DATETIME NOT NULL,
	StartTime DATETIME NOT NULL,
	EndTime DATETIME NOT NULL
)

CREATE TABLE AcceptedReservations (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ReservationsId INT FOREIGN KEY REFERENCES Reservations(Id) NOT NULL,
	AdminId INT FOREIGN KEY REFERENCES Admins(Id) NOT NULL,
)