CREATE TABLE Åbningstider (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HverdagStart DATETIME NOT NULL,
	HverdagSlut DATETIME NOT NULL,
	WekkendStart DATETIME NOT NULL,
	WeekendSlut DATETIME NOT NULL
)

CREATE TABLE Administratorer (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Fornavn NVARCHAR(MAX) NOT NULL,
	Efternavn NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
	Kodeord NVARCHAR(MAX) NOT NULL
)

Create TABLE Gader (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Gadenavn NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Byer (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Bynavn NVARCHAR(MAX) NOT NULL,
	Postnummer INT NOT NULL
)

CREATE TABLE Adresser (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ById INT FOREIGN KEY REFERENCES Byer(Id) NOT NULL,
	GaderId INT FOREIGN KEY REFERENCES Gader(Id) NOT NULL,
	Nr INT NOT NULL
)

CREATE TABLE Foreninger (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AdresseId INT FOREIGN KEY REFERENCES Adresser(Id) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Foreningsledere (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ForeningsId INT FOREIGN KEY REFERENCES Foreninger(Id) NOT NULL,
	Fornavn NVARCHAR(MAX) NOT NULL,
	Efternavn NVARCHAR(MAX) NOT NULL,
	Tlf INT NOT NULL,
)

CREATE TABLE Aktiviteter (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Navn NVARCHAR(MAX) NOT NULL,
	Pladsoptag INT NOT NULL
)

CREATE TABLE Reservationer (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AktivitetsId INT FOREIGN KEY REFERENCES Aktiviteter(Id) NOT NULL,
	Godkendt BIT NOT NULL,
	StartDato DATETIME NOT NULL,
	SlutDato DATETIME NOT NULL
)

CREATE TABLE ReservationsTid (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ReservationsId INT FOREIGN KEY REFERENCES Reservationer(Id) NOT NULL,
	Dato DATETIME NOT NULL,
	StartTid DATETIME NOT NULL,
	SlutTid DATETIME NOT NULL
)

CREATE TABLE GodkendteReservationer (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ReservationsId INT FOREIGN KEY REFERENCES Reservationer(Id) NOT NULL,
	AdminId INT FOREIGN KEY REFERENCES Administratorer(Id) NOT NULL,
)